version: "3"
services:
  db:
    container_name: "db"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=db
    ports:
      - "5433:5432"
    networks:
      - custom

  redis:
    container_name: "redis"
    image: redislabs/redismod
    ports:
      - '6379:6379'

  redisinsight:
    container_name: "redisinsight"
    image: redislabs/redisinsight:latest
    ports:
      - '8001:8001'

  pgadmin:
      container_name: pgadmin4_container
      image: dpage/pgadmin4
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: root@root.com
        PGADMIN_DEFAULT_PASSWORD: root
      ports:
        - '5050:80'
      networks:
        - custom

networks:
  custom:
    driver: bridge
