"""update3

Revision ID: 0cfc0b3071ad
Revises: dce137532372
Create Date: 2023-06-30 15:28:52.093399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cfc0b3071ad'
down_revision = 'dce137532372'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
