"""update1

Revision ID: 17300450d0a9
Revises: ff8be392f893
Create Date: 2023-06-30 15:14:06.251718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17300450d0a9'
down_revision = 'ff8be392f893'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
