"""update1

Revision ID: 473590bb10ed
Revises: 17300450d0a9
Create Date: 2023-06-30 15:17:12.024947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '473590bb10ed'
down_revision = '17300450d0a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
