"""update1

Revision ID: 647a69b21458
Revises: 6af6472adfda
Create Date: 2023-06-30 15:19:31.754298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '647a69b21458'
down_revision = '6af6472adfda'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
