"""initdb

Revision ID: 95723a0b1eb5
Revises:
Create Date: 2023-07-14 20:41:23.207783

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "95723a0b1eb5"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chains",
        sa.Column("chain_id", sa.Integer(), nullable=False),
        sa.Column("target_channel", sa.String(), nullable=True),
        sa.Column(
            "source_urls",
            sa.ARRAY(postgresql.JSON(astext_type=sa.Text())),
            nullable=True,
        ),
        sa.Column("parsing_type", sa.String(), nullable=True),
        sa.Column("parsing_time", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("additional_text", sa.String(), nullable=True),
        sa.Column("active_due_date", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("chain_id"),
    )
    op.create_table(
        "users",
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("chains_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["chains_id"],
            ["chains.chain_id"],
        ),
        sa.PrimaryKeyConstraint("chat_id"),
    )
    op.create_table(
        "posts",
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("chain_id", sa.Integer(), nullable=True),
        sa.Column("user_chat_id", sa.Integer(), nullable=True),
        sa.Column("is_sent", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["chain_id"],
            ["chains.chain_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_chat_id"],
            ["users.chat_id"],
        ),
        sa.PrimaryKeyConstraint("post_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("posts")
    op.drop_table("users")
    op.drop_table("chains")
    # ### end Alembic commands ###
