"""update2

Revision ID: d588ba9121f8
Revises: 647a69b21458
Create Date: 2023-06-30 15:22:29.876391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd588ba9121f8'
down_revision = '647a69b21458'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
