"""update3

Revision ID: dec7ddc5ef07
Revises: 0cfc0b3071ad
Create Date: 2023-06-30 16:13:50.090468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dec7ddc5ef07'
down_revision = '0cfc0b3071ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
